SELECT * FROM CARDAPIO_PIZZA;
SELECT * FROM FORMA_PAGAMENTO;
SELECT * FROM PEDIDO;

INSERT INTO CARDAPIO_PIZZA (CODIGO, DESCRICAO, NOME, VALOR) VALUES 
(1, 'Catupiry, azeitonas e orégano.', 'CATUPIRY', 50.0),
(2, 'Mussarela, catupiry, provolone, parmesão ralado, gorgonzola.', 'CINCO QUEIJOS', 55.0),
(3, 'Mussarela ou catupiry, rodelas de tomate, parmesão ralado, gorgonzola.', 'DO PAPA', 52.0),
(4, 'Mussarela e catupiry.', 'DOIS QUEIJOS', 50.0),
(5, 'Gorgonzola, azeitonas e orégano.', 'GORGONZOLA', 50.0),
(6, 'Mussarela salpicada com alho.', 'GRATINDADA', 50.0),
(7, 'Mussarela, molho de tomate, manjericão, parmesão ralado.', 'MARGUERITA', 52.0),
(8, 'Mussarela, orégano e azeitona.', 'MUSSARELA', 45.0),
(9, 'Mussarela com parmesão ralado e rodelas de tomate.', 'NAPOLITANA', 50.0),
(10, 'Fatias de provolone e azeitonas.', 'PROVOLONE', 50.0),
(11, 'Mussarela, catupiry, provolone, parmesão ralado.', 'QUATRO QUEIJOS', 55.0),
(12, 'Aliche importado com tomate e parmesão ralado.', 'ALICHE', 48.0),
(13, 'Atum, cebola e azeitona.', 'ATUM', 48.0),
(14, 'Atum coberto com catupiry.', 'ATUM C/ CATUPIRY', 50.0),
(15, 'Atum coberto com mussarela.', 'ATUM C/ MUSSARELA', 50.0),
(16, 'Camarão, atum, ovos, azeitonas e mussarela.', 'CHOPPIZZA', 50.0),
(17, 'Mussarela, palmito, atum, ervilhas, ovos, cebola, azeitonas.', 'PERUANA', 48.0),
(18, 'Mussarela, aliche, rodelas de tomate e azeitonas.', 'ROMANA', 48.0),
(19, 'Presunto fatiado, azeitonas pretas, mussarela.', 'À MODA DA CASA', 52.0),
(20, 'Presunto fatiado, ovos, azeitonas pretas, mussarela.', 'À MODA ANTIGA', 52.0),
(21, 'Mussarela, calabresa, bacon e cebola.', 'ALEMÃ', 48.0),
(22, 'Calabresa moída, rodelas de tomate, parmesão ralado, cebola, azeitonas e pimenta.', 'BAIANA', 48.0),
(23, 'Bacon, rodelas de tomate, cebola e azeitonas.', 'BACON', 48.0),
(24, 'Bacon fatiado coberta com catupiry.', 'BACON C/ CATUPIRY', 50.0),
(25, 'Bacon fatiado coberta com mussarela.', 'BACON C/ MUSSARELA', 50.0),
(26, 'Calabresa, cebola e azeitonas.', 'CALABRESA', 45.0),
(27, 'Calabresa, fatias de bacon e cebola.', 'CALABRESA C/ BACON', 50.0),
(28, 'Calabresa, coberta com catupiry.', 'CALABRESA C/ CATUPIRY', 50.0),
(29, 'Calabresa, coberta com mussarela.', 'CALABRESA C/ MUSSARELA', 50.0),
(30, 'Presunto picado, champignon, mussarela e bacon.', 'DA HORA', 48.0),
(31, 'Calabresa picada, cebola e azeitonas.', 'ESPANHOLA', 52.0),
(32, 'Presunto picado, ovos, catupiry, coberta com mussarela.', 'FRANCESA', 52.0),
(33, 'Presunto fatiado, azeitonas verdes picadas coberta com mussarela ou catupiry.', 'FORNEIRO', 52.0),
(34, 'Lombo, champignon, azeitonas e mussarela.', 'ITALIANA', 52.0),
(35, 'Lombo Canadense, cebola e azeitonas.', 'LOMBINHO', 50.0),
(36, 'Lombo defumado coberto com catupiry.', 'LOMBO C/ CATUPIRY', 52.0),
(37, 'Mussarela, palmito, atum, ervilhas, ovos, cebola, azeitonas.', 'PAULISTA', 50.0),
(38, 'Presunto, catupiry, ervilhas, champignon, ovos, mussarela.', 'PIZZAIOLO', 52.0),
(39, 'Mussarela, presunto, ovos, cebola, azeitonas.', 'PORTUGUESA', 52.0),
(40, 'Calabresa moída coberta com mussarela ou catupiry.', 'TOSCANA', 50.0),
(41, 'Frango desfiado temperado com catupiry e azeitonas.', 'FRANGO C/ CATUPIRY', 52.0),
(42, 'Frango desfiado com milho com cobertura de catupiry ou mussarela.', 'FRANGO', 48.0),
(43, 'Alho e óleo, parmesão ralado e azeitonas.', 'ALHO E ÓLEO', 50.0),
(44, 'Mussarela, palmito, bacon, ovos e cebola.', 'AMERICANA', 52.0),
(45, 'Champignon e cebola com mussarela ou calabresa', 'CHAMPIGNON', 50.0),
(46, 'Champignon, alcaparra, catupiry e provolone.', 'CHAMPIGNON C/ ALCAPARRAS', 52.0),
(47, 'Escarola, mussarela e aliche.', 'ESCAROLA', 48.0),
(48, 'Escarola, palmito, ervilhas, milho, mussarela ou catupiry.', 'JARDINEIRA', 50.0),
(49, 'Milho verde, catupiry ou mussarela.', 'MILHO VERDE', 52.0),
(50, 'Palmito, azeitonas pretas e mussarela.', 'PALMITO', 50.0),
(51, 'Mussarela, Champignon e bacon.', 'SICILIANA', 52.0),
(52, 'Escarola, alho, champignon, milho e mussarela.', 'VEGETARIANA', 50.0);

INSERT INTO FORMA_PAGAMENTO (CODIGO, NOME) VALUES  
(1, 'Crédito'),
(2, 'Débito'),
(3, 'Dinheiro');